config/routes.rb
ELearn::Application.routes.draw do

root             :to =>'screens#home'
devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users
  resources  :users
  resources  :courses
  resources  :categories
  
  

  match '/help',   :to => 'screens#help'
  match '/about',  :to  =>'screens#about'
  match '/contact', :to  =>'screens#contact'
  match '/auth/:provider/callback', to: 'authentication#create'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category_name
  has_many :courses , dependent: :destroy
  validates :category_name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	#before_filter :authenticate_user!, only:[:create,:edit,:update,:delete]
   before_filter :admin_user_check, :only => [:new, :edit, :create, :destroy]
  def new
  	@category=Category.new
  end

  def create
  	@category=Category.new(params[:category])
  	if @category.save
  		flash[:Success] = "Successfully created..."
  		redirect_to @category
  	else
  		flash[:error] = "Failed..."
  		render 'new'
  	end

  	
  end

  def edit
  	@category=Category.find(params[:id])
  end

  def update
  	@category=Category.find(params[:id])
  	if @category.update_attributes(params[:category])
  		flash[:Success] = "Successfully Updated..."
  		redirect_to @category
  	else
  		flash[:error] = "Failed..."
  		render 'new'
  	end

  	
  end

  def show
  	@category=Category.find(params[:id])
  end

  def index
  	@category=Category.all
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Successfully deleted..."
    redirect_to categories_url
  end


 
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Categories - edit</h1>
<div class="row">
  <div class="span6 offset3">

<%= form_for(@category) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :category_name %>
<%= f.text_field :category_name %>
<%= f.submit "Update", class: "btn btn-primary btn-large" %>
<% end %>
</div></div>

app/views/categories/index.html.erb
<h1>Categories - all categories</h1>


<% @category.each do |category| %>
<% if current_user.admin? %>
<%= link_to "Edit",edit_category_path(category) %>
<%= link_to "Delete", category,method: :delete, data: {confirm: "You Sure"},title: category.category_name %>
<% end %>
<%= category.category_name %>
<br/>
<br/>


<% end %>

app/views/categories/new.html.erb
<h1>Categories - create</h1>
<div class="row">
  <div class="span6 offset3">
<%= form_for(@category) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :category_name %>
<%= f.text_field :category_name %>
<%= f.submit "Submit"  , class: "btn btn-primary btn-large"  %>
<% end %>
</div></div>

app/views/categories/show.html.erb
<h1>Categories - show</h1>
<% if current_user.admin? %>
<%= link_to "Edit", edit_category_path %>
<%= link_to "Delete", @category, method: :delete, data:{confirm: "You Sure?"}, title: @category.category_name %><% end %>
<%= @category.category_name %>