config/routes.rb
ELearn::Application.routes.draw do

root             :to =>'screens#home'
devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users
  resources  :users
  resources  :courses
  resources  :categories
  
  

  match '/help',   :to => 'screens#help'
  match '/about',  :to  =>'screens#about'
  match '/contact', :to  =>'screens#contact'
  match '/auth/:provider/callback', to: 'authentication#create'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
<%= link_to "E - Learn", root_path %>
	</small>
	<nav>
<ul>
<li><%= link_to "About",   about_path %></li>
<li><%= link_to "Contact", contact_path %></li>

</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "E-Learn",root_path,id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home",root_path %></li>
						<li><%= link_to "Help",help_path %></li>

						<% if signed_in? %>
						



						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories<b class="caret"></b>
							</a>

							<ul class="dropdown-menu">
								<li><%= link_to "Categories",categories_path %></li>
								
								<% if current_user.admin? %>
						<li><%= link_to "Add Category", new_category_path %></li>
							<% end %>

							</ul>
						</li>

							<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses<b class="caret"></b>
							</a>

							<ul class="dropdown-menu">
								<li><%= link_to  "Courses", courses_path %></li>
								
								<% if current_user.admin? %>
							<li><%= link_to "New Course", new_course_path %></li>
								
							<% end %>

							</ul>
						</li>



						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Users",users_path %></li>
								
						<% if current_user.admin? %>
								<li><%= link_to "New User", new_user_path %></li>
								<% end %>
								
							</ul>
						</li>



						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to  "Profile", current_user %></li>
								<li><%= link_to  "Settings", edit_user_registration_path(current_user) %></li>
								<li class='divider'></li>
								<li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
							</ul>
						</li>
						<% else %>
						<li><%= link_to "Register", new_user_registration_path %></li>
						<li><%= link_to "Sign in", user_session_path %></li>
						<% end %>
						
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_validation_messages.html.erb
<% flash.each do|key, value| %>

		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>E_Learn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<%= render 'layouts/validation_messages' %>

 <%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) %>
</div>
</body>
</html>